Add a caption
Chainmail-Studios/Astromine pull request #415
Opened 2021-05-16 14:31 UTC by MeMasterMind

Nothing much, I added the little "about" caption in the beginning of the README, changed `downloading` to `How to Download.` Just some little improvements to make it look professional  :)

2021-05-16 23:44 UTC, shedaniel requested changes

2021-05-16 23:44 UTC, shedaniel commented on README.md
> +Explore the space, witness the space, die in the space!
Can we not change this part, this is unnecessary

2021-05-17 10:11 UTC, MeMasterMind reviewed
okay

2021-05-18 16:49 UTC, shedaniel commented
Please update the PR accordingly.

2021-05-19 09:26 UTC, MeMasterMind commented
I can't, it says I can't approve it myself. A moderator needs to do that.
<img width="547" alt="Untitled" src="https://user-images.githubusercontent.com/64348757/118789315-49655800-b8b2-11eb-8c2e-c4e0dba2d1ee.png">

2021-05-19 09:52 UTC, shedaniel commented
You are not supposed to review on the PR, edit the branch.

2021-05-19 15:58 UTC, MeMasterMind commented
there. Sorry for the inconvinience, I am not wuite much familiar with the pull request system.

2021-05-19 16:04 UTC, shedaniel approved these changes

2021-05-19 16:04 UTC, merged